---
- name: restart cron
  service:
    name: cron
    state: restarted

- name: update tzdata
  command: dpkg-reconfigure -f noninteractive tzdata

- name: restart ssh
  service: name=ssh state=restarted

- name: reconfigure locale
  command: dpkg-reconfigure locales --frontend noninteractive

- name: reboot
  reboot:
    reboot_timeout: 1200